version: "3"


volumes:
  ckan_storage:
  pg_data:
  solr_data:

services:

  nginx:
    container_name: nginx
    image: ckan-docker-nginx
      
    networks:
      - webnet
      - ckannet
    depends_on:
      - ckan
          #condition: service_healthy
    ports:
      - "0.0.0.0:8443:443"
    
  ckan:
    container_name: ckan
    image: ckan-docker-ckan
    networks:
      - ckannet
      - dbnet
      - solrnet
      - redisnet
    
    depends_on:
      - db
        #condition: service_healthy
      - solr
        #condition: service_healthy
      - redis
        #condition: service_healthy
    volumes:
      - ckan_storage:/var/lib/ckan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5000"]
    
  datapusher:
    container_name: datapusher
    networks:
      - ckannet
      - dbnet
    image: ckan/ckan-base-datapusher:0.0.20
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8800"]

  db:
    container_name: db
    image: ckan-docker-db 

    networks:
      - dbnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - CKAN_DB_USER=ckandbuser
      - CKAN_DB_PASSWORD=ckandbpassword
      - CKAN_DB=ckandb
      - DATASTORE_READONLY_USER=datastore_ro
      - DATASTORE_READONLY_PASSWORD=datastore
      - DATASTORE_DB=datastore
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
     
  solr:
    container_name: solr
    networks:
      - solrnet
    image: ckan/ckan-solr:2.10-solr9
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  redis:
    container_name: redis
    image: redis:6
    networks:
      - redisnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
    
networks:
  webnet:
  ckannet:
  solrnet:
    internal: true
  dbnet:
    internal: true
  redisnet:
    internal: true
